from __future__ import annotations

import json
import os
import stat
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

from h2c_3mf_report.api import AnalyzeOptions, analyze_path
from h2c_3mf_report.archive import classify_archive
from h2c_3mf_report.duration import parse_duration_seconds
from h2c_3mf_report.profiles import ProfileConfig
from h2c_3mf_report.slicer import SlicerRequest, run_slicer


def _write_3mf(path: Path, members: dict[str, str | bytes]) -> Path:
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name, payload in members.items():
            zf.writestr(name, payload)
    return path


def _slice_info(plates: list[tuple[int, list[dict[str, object]]]]) -> str:
    plate_xml = []
    for plate_index, filaments in plates:
        filament_xml = []
        for filament in filaments:
            attrs = " ".join(f'{key}="{value}"' for key, value in filament.items())
            filament_xml.append(f'<filament {attrs} custom_attr="preserved" />')
        plate_xml.append(f'<plate id="{plate_index}">' + "".join(filament_xml) + "</plate>")
    return """<?xml version="1.0" encoding="UTF-8"?>
<config>
  <source_file path="models/cube.stl" name="cube.stl" />
  %s
</config>
""" % "\n  ".join(plate_xml)


def _gcode(total_time: str = "48m 41s", grams: float = 12.34, length: float = 4200.0) -> str:
    return f"""; generated by fixture
; model printing time: {total_time}
; total estimated time: {total_time}
; total layer number = 42
; total filament length [mm]: {length}
; total filament volume [cm^3]: 9.87
; total filament weight [g]: {grams}
; custom slicer field: keep-me
; HEADER_BLOCK_END
G1 X1 Y1
"""


def test_duration_parser_accepts_common_slicer_forms() -> None:
    assert parse_duration_seconds("48m 41s") == 2921
    assert parse_duration_seconds("2h 36m 25s") == 9385
    assert parse_duration_seconds("1d 4h 12m 9s") == 101529
    assert parse_duration_seconds("40m") == 2400
    assert parse_duration_seconds("95s") == 95
    assert parse_duration_seconds("01:02:03") == 3723


def test_classifies_sliced_by_archive_contents_not_filename(tmp_path: Path) -> None:
    path = _write_3mf(
        tmp_path / "misleading.3mf",
        {
            "Metadata/plate_1.gcode": _gcode(),
            "Metadata/slice_info.config": _slice_info([(1, [{"id": 1, "type": "PLA", "color": "000000", "used_m": 4.2, "used_g": 12.34}])]),
        },
    )

    classification = classify_archive(path)

    assert classification.source_kind == "sliced_gcode_3mf"
    assert classification.contains_sliced_gcode is True
    assert classification.contains_slice_info is True
    assert classification.plate_gcode_members == {1: "Metadata/plate_1.gcode"}


def test_extracts_single_plate_multi_color_report(tmp_path: Path) -> None:
    path = _write_3mf(
        tmp_path / "single_multi.gcode.3mf",
        {
            "Metadata/plate_1.gcode": _gcode(total_time="2h 31m 42s", grams=59.63, length=18720.0),
            "Metadata/slice_info.config": _slice_info(
                [
                    (
                        1,
                        [
                            {"id": 1, "type": "PLA", "tray_info_idx": "GFA00", "color": "000000", "used_m": 8.4, "used_g": 26.75, "group_id": 0, "nozzle_diameter": 0.4, "volume_type": "High Flow", "used_for_object": "true", "used_for_support": "false"},
                            {"id": 2, "type": "PLA", "tray_info_idx": "GFA01", "color": "#ffffff", "used_m": 10.32, "used_g": 32.88, "group_id": 0, "nozzle_diameter": 0.4},
                        ],
                    )
                ]
            ),
        },
    )

    report = analyze_path(path)

    assert report["schema_name"] == "h2c-3mf-report.v1"
    assert report["status"] == "ok"
    assert report["source_kind"] == "sliced_gcode_3mf"
    assert report["totals"]["plate_count"] == 1
    assert report["totals"]["filament_used_g_from_slice_info"] == 59.63
    assert report["totals"]["filament_used_m_from_slice_info"] == 18.72
    assert report["totals"]["filament_weight_g_from_gcode"] == 59.63
    assert report["totals"]["print_time_seconds"] == 9102
    plate = report["plates"][0]
    assert plate["colors"] == ["#000000", "#FFFFFF"]
    assert plate["filament_types"] == ["PLA"]
    assert plate["gcode"]["unknown_fields"] == {"custom slicer field": "keep-me"}
    assert plate["filaments"][0]["raw_attributes"] == {"custom_attr": "preserved"}
    assert report["source_files"] == [{"path": "models/cube.stl", "name": "cube.stl"}]


def test_extracts_multi_plate_and_multi_material_totals(tmp_path: Path) -> None:
    path = _write_3mf(
        tmp_path / "multi_plate.gcode.3mf",
        {
            "Metadata/plate_1.gcode": _gcode(total_time="40m", grams=10.0, length=1000),
            "Metadata/plate_2.gcode": _gcode(total_time="95s", grams=20.0, length=2000),
            "Metadata/slice_info.config": _slice_info(
                [
                    (1, [{"id": 1, "type": "PLA", "color": "112233", "used_m": 1.0, "used_g": 10.0}]),
                    (2, [{"id": 2, "type": "PETG", "color": "445566", "used_m": 2.0, "used_g": 20.0}]),
                ]
            ),
        },
    )

    report = analyze_path(path)

    assert [plate["plate_index"] for plate in report["plates"]] == [1, 2]
    assert report["totals"]["plate_count"] == 2
    assert report["totals"]["filament_used_g_from_slice_info"] == 30.0
    assert report["totals"]["filament_used_m_from_slice_info"] == 3.0
    assert report["totals"]["filament_weight_g_from_gcode"] == 30.0
    assert report["totals"]["print_time_seconds"] == 2495.0
    assert report["plates"][1]["filament_types"] == ["PETG"]


def test_missing_slice_info_yields_partial_warning_but_parses_gcode(tmp_path: Path) -> None:
    path = _write_3mf(tmp_path / "missing_slice_info.gcode.3mf", {"Metadata/plate_1.gcode": _gcode()})

    report = analyze_path(path)

    assert report["status"] == "ok"
    assert report["contains_slice_info"] is False
    assert report["totals"]["print_time_seconds"] == 2921
    codes = [warning["code"] for warning in report["warnings"]]
    assert "SLICE_INFO_MISSING" in codes


def test_missing_gcode_yields_gcode_missing_warning_and_raw_classification(tmp_path: Path) -> None:
    path = _write_3mf(
        tmp_path / "missing_gcode.3mf",
        {"Metadata/slice_info.config": _slice_info([(1, [{"id": 1, "type": "PLA", "color": "ABCDEF", "used_m": 1.0, "used_g": 3.0}])])},
    )

    report = analyze_path(path)

    assert report["status"] == "error"
    assert report["source_kind"] == "raw_project_3mf"
    assert report["contains_slice_info"] is True
    assert report["contains_sliced_gcode"] is False
    assert report["totals"]["print_time_seconds"] is None
    assert report["errors"][0]["code"] == "UNSLICED_FILE"


def test_raw_unsliced_project_returns_unsliced_error_with_unknown_estimates(tmp_path: Path) -> None:
    path = _write_3mf(tmp_path / "raw.3mf", {"3D/3dmodel.model": "<model />"})

    report = analyze_path(path)

    assert report["status"] == "error"
    assert report["source_kind"] == "raw_project_3mf"
    assert report["totals"]["print_time_seconds"] is None
    assert report["errors"][0]["code"] == "UNSLICED_FILE"
    assert report["errors"][0]["type"].endswith("/unsliced-file")


def test_invalid_archive_returns_problem_details_error(tmp_path: Path) -> None:
    path = tmp_path / "invalid.3mf"
    path.write_text("not zip", encoding="utf-8")

    report = analyze_path(path)

    assert report["status"] == "error"
    assert report["source_kind"] == "invalid_archive"
    assert report["errors"][0]["code"] == "INVALID_ARCHIVE"
    assert report["errors"][0]["status"] == 400


def test_unsafe_archive_path_returns_invalid_archive_error(tmp_path: Path) -> None:
    path = _write_3mf(tmp_path / "unsafe.3mf", {"../escape.gcode": "boom"})

    report = analyze_path(path)

    assert report["status"] == "error"
    assert report["errors"][0]["code"] == "INVALID_ARCHIVE"


def test_placeholder_filament_255_ignored_by_default(tmp_path: Path) -> None:
    path = _write_3mf(
        tmp_path / "placeholder.gcode.3mf",
        {
            "Metadata/plate_1.gcode": _gcode(grams=3.0),
            "Metadata/slice_info.config": _slice_info(
                [(1, [{"id": 255, "type": "PLA", "color": "FFFFFF", "used_m": 99, "used_g": 99}, {"id": 1, "type": "PLA", "color": "000000", "used_m": 1, "used_g": 3}])]
            ),
        },
    )

    default_report = analyze_path(path)
    included_report = analyze_path(path, AnalyzeOptions(include_placeholder_filaments=True))

    assert [item["id"] for item in default_report["plates"][0]["filaments"]] == [1]
    assert [item["id"] for item in included_report["plates"][0]["filaments"]] == [255, 1]


def test_cli_emits_valid_json_for_multiple_inputs_jsonl(tmp_path: Path) -> None:
    good = _write_3mf(tmp_path / "good.gcode.3mf", {"Metadata/plate_1.gcode": _gcode(), "Metadata/slice_info.config": _slice_info([(1, [{"id": 1, "type": "PLA", "color": "000", "used_m": 1, "used_g": 12.34}])])})
    raw = _write_3mf(tmp_path / "raw.3mf", {"3D/3dmodel.model": "<model />"})

    project_root = Path(__file__).resolve().parents[1]
    env = {**os.environ, "PYTHONPATH": str(project_root / "src")}
    result = subprocess.run(
        [sys.executable, "-m", "h2c_3mf_report", "--jsonl", str(good), str(raw)],
        cwd=project_root,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )

    assert result.returncode == 2
    rows = [json.loads(line) for line in result.stdout.splitlines()]
    assert [row["file"] for row in rows] == [good.name, raw.name]
    assert rows[0]["status"] == "ok"
    assert rows[1]["errors"][0]["code"] == "UNSLICED_FILE"


def test_cli_output_dir_writes_one_report_per_input(tmp_path: Path) -> None:
    good = _write_3mf(tmp_path / "good.gcode.3mf", {"Metadata/plate_1.gcode": _gcode(), "Metadata/slice_info.config": _slice_info([(1, [{"id": 1, "type": "PLA", "color": "000", "used_m": 1, "used_g": 12.34}])])})
    output_dir = tmp_path / "reports"

    project_root = Path(__file__).resolve().parents[1]
    env = {**os.environ, "PYTHONPATH": str(project_root / "src")}
    result = subprocess.run(
        [sys.executable, "-m", "h2c_3mf_report", "--output-dir", str(output_dir), str(good)],
        cwd=project_root,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )

    assert result.returncode == 0
    report_path = output_dir / "good.gcode.3mf.json"
    assert report_path.exists()
    assert json.loads(report_path.read_text())["status"] == "ok"


def test_slicer_command_builder_and_fake_runner_success(tmp_path: Path) -> None:
    input_path = _write_3mf(tmp_path / "raw.3mf", {"3D/3dmodel.model": "<model />"})
    output_path = tmp_path / "work" / "raw.gcode.3mf"
    machine = tmp_path / "h2c_machine.json"
    process = tmp_path / "process.json"
    filament = tmp_path / "pla.json"
    for path in [machine, process, filament]:
        path.write_text("{}", encoding="utf-8")
    fake_slicer = tmp_path / "fake-slicer"
    fake_slicer.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    fake_slicer.chmod(fake_slicer.stat().st_mode | stat.S_IXUSR)
    config = ProfileConfig(machine_profile=machine, process_profile=process, filament_profiles=[filament], bed_type="Textured PEI Plate")

    def fake_runner(command: list[str], cwd: Path, timeout: int | None):
        output_path.parent.mkdir(parents=True, exist_ok=True)
        _write_3mf(output_path, {"Metadata/plate_1.gcode": _gcode(), "Metadata/slice_info.config": _slice_info([(1, [{"id": 1, "type": "PLA", "color": "000000", "used_m": 1, "used_g": 12.34}])])})
        return subprocess.CompletedProcess(command, 0, "", "")

    request = SlicerRequest(input_path, output_path, "bambu-studio", fake_slicer, config, tmp_path / "work")
    result = run_slicer(request, runner=fake_runner)

    assert result.ok is True
    assert result.output_path == output_path
    assert result.profiles is not None
    assert result.profiles["machine"]["basename"] == "h2c_machine.json"
    assert "--load-settings" in result.command
    assert "--load-filaments" in result.command


def test_slicer_missing_executable_is_fakeable_error(tmp_path: Path) -> None:
    request = SlicerRequest(
        input_path=tmp_path / "in.3mf",
        output_path=tmp_path / "out.gcode.3mf",
        slicer="bambu-studio",
        slicer_path=tmp_path / "missing-slicer",
        profile_config=ProfileConfig(),
        work_dir=tmp_path,
    )

    result = run_slicer(request, runner=lambda *_: pytest.fail("runner should not be called"))

    assert result.ok is False
    assert result.error_code == "SLICER_NOT_FOUND"


def test_optional_real_fixture_dir_is_gated() -> None:
    fixture_dir = os.environ.get("H2C_3MF_FIXTURE_DIR")
    if not fixture_dir:
        pytest.skip("H2C_3MF_FIXTURE_DIR not set; real H2C validation gated on Board-provided fixtures/profiles/binaries")
    paths = sorted(Path(fixture_dir).glob("*.3mf")) + sorted(Path(fixture_dir).glob("*.gcode.3mf"))
    assert paths, "H2C_3MF_FIXTURE_DIR must contain at least one 3MF fixture"
    for path in paths:
        report = analyze_path(path)
        assert report["schema_name"] == "h2c-3mf-report.v1"
